M48
; DRILL file {KiCad 7.0.9} date Fri Dec 15 21:41:48 2023
; FORMAT={2:4/ absolute / inch / suppress leading zeros}
; #@! TF.CreationDate,2023-12-15T21:41:48-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.9
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH,TZ
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0315
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0433
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C0.1260
%
G90
G05
T1
X38616Y-32985
X40584Y-32985
T2
X27216Y-32040
X29184Y-32040
T3
X35850Y-31900
X35850Y-44250
T0
M30
